import React from "react";
import styles from "./AboutSection.module.css";
import Box from "../../atoms/Box";
export default function AboutSection() {
  return (
    <div className={styles.container}>
      <div className={styles.topContainer}>
        <Box fontColor="white" fullBorderRadius="full" color="black">
          <p className={styles.topFont}>About How Busy Is Toon </p>
        </Box>
      </div>

      <Box color="grey" fontColor="black" fullBorderRadius="bottom">
        <div className={styles.LinkBox}>
          <div className={styles.subHeading}>
            <h1 lassName={styles.subHeadingText}>What are we doing?</h1>
          </div>
          <p className={styles.contentText}>
            How Busy Is Toon is here to help you feel safe and prepared when
            visiting your city centre. You have access to still images updated
            every five minutes from around the city centre, access to still
            images updated every 5 minutes of traffic cams of popular roads in
            and out of the city centre, live data on car park capacity, real
            time bus data, and up to date rules and safety guidance from
            councils and government.
          </p>
        </div>
      </Box>
      <Box color="grey" fontColor="black" fullBorderRadius="bottom">
        <div className={styles.LinkBox}>
          <div className={styles.subHeading}>
            <h1 lassName={styles.subHeadingText}>Who’s involved?</h1>
          </div>
          <p className={styles.contentText}>
            The platform was built in collaboration with Newcastle City Council,
            NE1, Newcastle University’s Research Software Engineering team, and
            hedgehog lab, using data from the Urban Observatory, and data
            analytics from National Innovation Centre for Data.
          </p>
        </div>
      </Box>
      <Box color="grey" fontColor="black" fullBorderRadius="bottom">
        <div className={styles.LinkBox}>
          <div className={styles.subHeading}>
            <h1 lassName={styles.subHeadingText}>
              Use of Data & Privacy Notice
            </h1>
          </div>
          <p className={styles.contentText}>
            The traffic light status on the homepage is based on footfall data
            from Northumberland Street only, generated by cameras using computer
            vision technology. The information is transmitted back to the Urban
            Observatory and the website is automatically updated using the data
            collected. The footage is not routinely monitored. Other data shared
            on this site including traffic cameras and parking information are
            also managed by the Urban Observatory (include link to their site).
            More information is available in the Urban Observatory's privacy
            statement
          </p>
        </div>
      </Box>
      <Box color="grey" fontColor="black" fullBorderRadius="bottom">
        <div className={styles.LinkBox}>
          <div className={styles.subHeading}>
            <h1 lassName={styles.subHeadingText}>
              Our Partners & Collaborators
            </h1>
          </div>
          <p className={styles.contentText}>
            How Busy Is Toon was 1 of 11 funded collaborative projects through
            the MHCLG Local Digital COVID-19 Challenge. Research was conducted
            by hedgehog lab with people all around the UK who gave valuable
            feedback and insight into what they would like to see on this
            website.
          </p>
        </div>
      </Box>
    </div>
  );
}
